### ISSUE TITLE
Create Project Proposal Paper

### ISSUE THREAD

**Issue by peterdelevoryas** [afrisone/csci4502-datamining#10]
This is the description of the sections of the proposal paper from the [course website](https://sites.google.com/a/colorado.edu/csci-4502/proj).
- Problem statement/motivation
- Literature survey (previous work)
- Proposed Work
  - E.g., what do you need to do for data collection, pre-processing (cleaning, integrating, transforming, etc.), process for derived data, design, evaluation...
  - Describe how it is different than what has been done previously from your literature survey
- Data set (make sure you *have* the data set!)
- Evaluation Methods
  - E.g., metrics, existing solutions, ...
- Tools
- Milestones
- Summary of peer review session

**Comment by iffig** [comment]
Hey guys! I took some notes from our "Peer Review Session" after our presentation. Here is some of the feedback/questions that we got from other students and the professor that we may want to consider addressing in our proposal: 

- Are we going to consider times of day, or just times of year?

- Would it be better to focus on newer data only, or are we going to consider the older data as well? 

- If we focus on older data how will we address the discrepancy between attributes for older data and newer data?

- The duration of some flights differs depending on the direction in which the plane travels and the wind direction, is this something we want to look into?
