### ISSUE TITLE
Add group under course website "Present" tab

### ISSUE THREAD

**Issue by peterdelevoryas** [afrisone/csci4502-datamining#4]
[Link to "Present" tab](https://sites.google.com/a/colorado.edu/csci-4502/demo-times)

- [x] Added group number and project title to presentation schedule
- [x] Added link to proposal slide deck
- [x] Scheduled group for specific time

**Comment by peterdelevoryas** [comment]
During the meeting this morning, we thought it would be good to do our presentation on the first day, so we added our group to the time slot 9:07 am, Feb 27. Still need to confirm this is ok with @iffig though!

**Comment by iffig** [comment]
@peterdelevoryas This works for me!

**Comment by peterdelevoryas** [comment]
Perfect!

**Comment by peterdelevoryas** [comment]
Finished linking the slideshow, here's evidence in case something bad happens: 
![2017-02-22-214619_667x391_scrot](https://cloud.githubusercontent.com/assets/8096834/23245257/6c110b98-f948-11e6-8eb0-9a948104d31d.png)
