### ISSUE TITLE
Create slide show pdf

### ISSUE THREAD

**Issue by peterdelevoryas** [afrisone/csci4502-datamining#5]
### Requirements (from course website, project description)
- Decriptive title of your project
- Descriptive title of your project
- Team members: first and last name of each member
- 2-3 sentence paragraph project description - *what interesting questions do you intend to answer?*
- What prior work has been done on your idea
- List of datasets to use (where found and whether it you have it downloaded)
- Proposed work: what do you need to do?
    - E.g., data cleaning, data preprocessing, data integration, etc.
- List of tool(s) you intend to use
- How you can evaluate your results

**Comment by peterdelevoryas** [comment]
Hey guys! Just to kind of formally outline what we're doing, I figured I would write a small document here, and we can discuss it or make changes to it, formalize it, etc.

# Questions

The questions we're asking are primarily in the interest of understanding current air transportation on-time performance, to help consumers make better choices about flying. Some of the things we're interested in knowing are,

- What time of day have the smallest flight delays?
- What part of the month have the smallest flight delays?
- What part of the year have the smallest flight delays?
- What parts of the world have the smallest flight delays?
- What factors contribute to flight delays?

# Data Visualization

Data visualization will be really helpful for answering most of our questions. To understand a lot of it, we just need the departure and arrival delay columns and the time the flight was scheduled for.

# Modeling
On the other hand, it might be harder to tell what causes flight delays from data visualization.
Although I think it will be difficult to accurately predict departure delays without a lot of scheduling information (what flights were scheduled before it, congestion at a airport, etc) or weather information, we can at least try to model the data and see what happens.

Since we are interested in continuous variables, it is entirely possible to just use linear regression, however I think, as we discussed a little bit at our meeting today, that it might be beneficial to use logistic regression, which is essentially linear regression when your output variable is a category or bucket. I'm only familiar with logistic regression because I am also taking machine learning this semester, which is why this part of our analysis will probably be less important than the data visualization portion.

**Comment by afrisone** [comment]
Thank you for putting this together! It looks awesome to me. I'm not entirely sure what to use for the modeling yet, but I do feel like after we start messing with the data, thinking of how to answer the question, etc, we will start playing with different modeling methods and find one that works. :)
