### ISSUE TITLE
Find data set

### ISSUE THREAD

**Issue by peterdelevoryas** [afrisone/csci4502-datamining#6]
Description of data set from course website:

> Size of data set - hopefully millions of data points. A few thousand is too small.

Some resources:

- [data.gov](https://www.data.gov/)
- [kaggle](https://www.kaggle.com/)
- [kdd](http://www.kdd.org/kdd2016/)

**Comment by peterdelevoryas** [comment]
One of the candidates we have so far is the [*Consumer Complaint Database*](https://catalog.data.gov/dataset/consumer-complaint-database), which is a data set with 705,362 records (pretty close to the "millions of data points" guideline), and has some interesting features, including the "Consumer complaint narrative", a block of text that the consumer issuing the complaint wrote. That, along with some other interesting attributes like "Timely response" and "Consumer disputed" could be used to build a model that might tell us something about the importance, or validity, of a consumer complaint, or the likelihood that a consumer will get a good response.

**Comment by afrisone** [comment]
I found one on Lending Club loan data. It's roughly 887k lines 

https://www.kaggle.com/wendykan/lending-club-loan-data

**Comment by Bhawth** [comment]
https://www.kaggle.com/giovamata/airlinedelaycauses

airline delays

**Comment by iffig** [comment]
Hey guys, here's one that I found. Its about crimes and such that occur on campuses across the US. Might be useful for coming up with ideas on how to stay safe and things like that. 
It looks like they have data for a lot of different colleges, so we could kind of pick and choose the data (location, years, etc.) that we want to work with. 

https://catalog.data.gov/dataset/campus-safety-and-security-survey-2013

**Comment by peterdelevoryas** [comment]
So, just to put it on the record, we decided during today's meeting that we would go with analyzing [on-time performance data](https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236&DB_Short_Name=On-Time), from the Bureau of Transportation Statistics. There is also some [supplementary](https://www.faa.gov/airports/airport_safety/airportdata_5010/) [data](https://www.ncdc.noaa.gov/data-access/quick-links#loc-clim) that we might use as well. Anyways, I'm gonna close this issue!
